# Render service configuration (declarative)
# See https://render.com/docs/deploy-using-render-yaml for details
services:
  - type: web
    name: todo-api-2-web
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      # APP_KEY and DB_* should be set in Render dashboard (do NOT commit secrets here)
      # - key: APP_KEY
      #   fromDatabase: secret-app-key
services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
